### ISSUE TITLE
运行安装脚本报错

### ISSUE THREAD

**Issue by imbalaomao** [QIN2DIM/juicity-installer#11]
具体报错如下：
```
root@vm20230128491:~# python3 <(curl -fsSL https://ros.services/juicy.py) install
Traceback (most recent call last):
  File "/dev/fd/63", line 25, in <module>
ImportError: cannot import name 'Literal' from 'typing' (/usr/lib/python3.7/typing.py)
```
似乎是无法导入一个库，我的服务器系统版本为Debian 11，Python版本为3.7（自带的）

**Comment by QIN2DIM** [comment]
瞳孔地震bro，这个脚本我用的全是 built-in lib，没想到 typing.Literal 竟然是 python3.8 才引入的特性，防不住啊

![image](https://github.com/QIN2DIM/juicity-installer/assets/62018067/3915a9be-4ca6-4197-84e0-e34d40372925)

**Comment by imbalaomao** [comment]
> 瞳孔地震bro，这个脚本我用的全是 built-in lib，没想到 typing.Literal 竟然是 python3.8 才引入的特性，防不住啊
> 
> ![image](https://user-images.githubusercontent.com/62018067/271047376-3915a9be-4ca6-4197-84e0-e34d40372925.png)

绝了……似乎这些VPS商自带的Debian 11系统，python版本都不尽相同……看来还是每次自己编译一个python 3.8更新进去为妙

**Comment by QIN2DIM** [comment]
> 绝了……似乎这些VPS商自带的Debian 11系统，python版本都不尽相同……看来还是每次自己编译一个python 3.8更新进去为妙

这么玩是吧，那我把脚本编译成一个 linux_amd64 可执行文件？

**Comment by imbalaomao** [comment]
> > 绝了……似乎这些VPS商自带的Debian 11系统，python版本都不尽相同……看来还是每次自己编译一个python 3.8更新进去为妙
> 
> 这么玩是吧，那我把脚本编译成一个 linux_amd64 可执行文件？

倒也还好哈哈哈，我手里的机器只有一台有这个问题，我已经编译了一个python 3.11放到了github gist，后面用的时候下载替换掉原来的python3就行
