### ISSUE TITLE
配置生成不出来

### ISSUE THREAD

**Issue by akaagiao1** [QIN2DIM/juicity-installer#3]
![image](https://github.com/QIN2DIM/juicity-installer/assets/94331537/78acc767-5d6c-4cbe-add6-c0c093bbb283)
我的vps是dv 的Debian 12 Last

**Comment by QIN2DIM** [comment]
看文档，juicy alias command 在刷新会话之后才生效，如果你不知道怎么刷新的话就重开一个 ssh 窗口连到服务器。

这个log 看起来是两个问题，你先把 alias 的问题解决了再重新发

**Comment by QIN2DIM** [comment]
已通过 execl 的方式自动重载 shell session:
- `install` 结束后可以直接使用 `juicy` 别名指令
- `remove` 结束后无法继续在当前窗口中继续使用 `juicy` 别名指令
